---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gpu
  dependsOn:
    - name: postgres-cluster
      namespace: databases
    - name: dragonfly-cluster
      namespace: databases
    - name: external-secrets
      namespace: security
    - name: rook-ceph
      namespace: rook-ceph
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 30m
  path: ./kubernetes/apps/selfhosted/immich/app
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: photos.kokoro.wtf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
