---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${KOPIUR_CLAIM:-${APP}}"
spec:
  accessModes:
    - ${PVC_ACCESSMODES:=ReadWriteOnce}
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: ${APP}
  resources:
    requests:
      storage: ${PVC_CAPACITY:=5Gi}
  storageClassName: ${KPVC_STORAGECLASS:=ceph-block}
