; Make sure to update the epoch time in the SOA records so coreDNS picks up the changes automatically
; https://www.epochconverter.com/

; SOA Records
$TTL 3600
$ORIGIN ctec.run.
@ 3600 IN SOA gateway.ctec.run. gateway.ctec.run. (
  1682790096         ; serial number (epoch timestamp)
  7200               ; refresh period
  3600               ; retry period
  1209600            ; expire time
  3600               ; minimum ttl
)

; NS Records
@                          IN  NS gateway.ctec.run.


; LAN
gateway                    IN  A  10.0.0.1
pikvm                      IN  A  10.0.0.50
pikvm2                     IN  A  10.0.0.51

; Trusted
shinobu                    IN  A 10.0.1.5
yuzu                       IN  A 10.0.1.50
poro                       IN  A 10.0.1.119
himari                     IN  A 10.0.1.120
petra                      IN  A 10.0.1.121

; Servers
shana                      IN  A  10.0.2.4
rem                        IN  A  10.0.2.5
ram                        IN  A  10.0.2.6
uiharu                     IN  A  10.0.2.10
sakura                     IN  A  10.0.2.12
miri                       IN  A  10.0.2.11
anya                       IN  A  10.0.2.13
ponyo                      IN  A  10.0.2.15

; IOT
prusa                      IN  A  10.0.3.110
printer                    IN  A  10.0.3.51

; Video

; Containers
main                       IN  A  10.5.0.2

; Incus
minio                      IN  A  10.0.2.90
talos                      IN  A  10.0.2.91
flexo                      IN  A  10.0.2.99

; CNAME records
cluster                    IN  CNAME  main.ctec.run.
nas                        IN  CNAME  shana.ctec.run.
