---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: '{{ .runner_token }}'
        token2: '{{ .runner_token2 }}'
  dataFrom:
    - extract:
        key: forgejo
