---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      forgejo-runner:
        type: statefulset
        replicas: 1

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        statefulset:
          volumeClaimTemplates:
            - name: data
              globalMounts:
                - path: /data
              accessMode: "ReadWriteOnce"
              size: 1Gi

        initContainers:
          register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.7.3@sha256:48b0539854bfc769fbf629725e089e35cfa1227ddedc7e45436b83bb9502ae27
            command:
              - "sh"
              - "-c"
              - >
                if [ ! -f /data/.runner ]; then
                  echo "Registering runner...";
                  forgejo-runner register --no-interactive \
                    --token $(RUNNER_TOKEN) \
                    --name $(RUNNER_NAME) \
                    --instance $(FORGEJO_INSTANCE_URL) \
                    --labels "$(LABELS)";
                else
                  echo "Runner already registered, skipping.";
                fi
            env:
              FORGEJO_INSTANCE_URL: http://forgejo-http.selfhosted.svc.cluster.local:3000
              LABELS: "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
            envFrom:
              - secretRef:
                  name: forgejo-runner-secret
        containers:
          daemon:
            image:
              repository: docker
              tag: 29.3.1-dind@sha256:4d90f1f6c400315c2dba96d3ec93c01e64198395cbba04f79d12adce4f737029
            resources:
              requests:
                cpu: 10m
                memory: 194Mi
              limits:
                memory: 194Mi
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.7.3@sha256:48b0539854bfc769fbf629725e089e35cfa1227ddedc7e45436b83bb9502ae27
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            command:
              - "sh"
              - "-c"
              - "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /config/config.yaml daemon"
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
        annotations:
          reloader.stakater.com/auto: "true"

    service:
      app:
        controller: *app
        ports:
          http:
            port: 45315

    persistence:
      config:
        type: configMap
        name: forgejo-runner-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true

      certs:
        type: emptyDir
      cache:
        type: emptyDir
