---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-tunnel
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .account_tag "t" .tunnel_id_new "s" .tunnel_secret_new) | b64enc }}
  dataFrom:
    - extract:
        key: cloudflare
