---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rtlamr2mqtt
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        rtlamr2mqtt.yaml: |
          general:
            listen_mode: true
            verbosity: info

          mqtt:
            host: 127.0.0.1   # still required for standalone, but no connection is made
  dataFrom:
    - extract:
        key: rtlamr2mqtt
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
