---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pgadmin
  values:
    controllers:
      pgadmin:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
            fsGroup: 5050
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: mirror.gcr.io/dpage/pgadmin4
              tag: 9.13@sha256:d243a4bcc02d2ee6b447c601692813531d2d0fbca18b583d9f7f9658da835d81
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 512M

    service:
      app:
        ports:
          http:
            port: 80

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.kokoro.wtf"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          pgadmin:
            app:
              - path: /var/lib/pgadmin
      server-json:
        enabled: true
        type: configMap
        name: servers-json
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json
