---
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: cdi
content: |-
  [plugins."io.containerd.cri.v1.runtime"]
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
    device_ownership_from_security_context = true
