---
apiVersion: v1alpha1
kind: EtcFileConfig
name: nfsmount.conf
mode: 0o644
contents: |
  [ NFSMount_Global_Options ]
  nfsvers=4.2
  hard=True
  nconnect=16
  noatime=True
  rsize=1048576
  wsize=1048576
