---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./embed.yaml
  - ./externalsecret.yaml
  - ./litellmproxy.yaml
  - ./nvidia-pool.yaml
  - ./serviceMonitor.yaml
  # - ./models/
