---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo-runner-old
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    configMaps:
      config:
        suffix: config
        data:
          runner.yaml: |-
            log:
              level: info

            runner:
              file: .runner
              capacity: 1
              envs:
                CLEEB: true
                DOCKER_HOST: tcp://127.0.0.1:2376
                DOCKER_TLS_VERIFY: 1
                DOCKER_CERT_PATH: /certs/client
              env_file: .env
              timeout: 3h
              insecure: false
              fetch_timeout: 5s
              fetch_interval: 2s
              labels: []

            cache:
              enabled: true
              dir: "/cache"
              host: ""
              port: 0

            container:
              network: "host"
              enable_ipv6: false
              privileged: false
              options: -v /certs/client:/certs/client
              workdir_parent: /workspace
                - /certs/client
              docker_host: ""

            host:
              # The parent directory of a job's working directory.
              # If it's empty, $HOME/.cache/act/ will be used.
              workdir_parent:
    controllers:
      forgejo-runner:
        type: statefulset
        replicas: 1

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        statefulset:
          volumeClaimTemplates:
            - name: data
              globalMounts:
                - path: /data
              accessMode: "ReadWriteOnce"
              size: 1Gi

        initContainers:
          register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.7.2@sha256:5be962a66390e54f0e56c89aafee48f521538d996df7c4e61af77915a4c2bd86
            command:
              - "sh"
              - "-c"
              - >
                if [ ! -f /data/.runner ]; then
                  echo "Registering runner...";
                  forgejo-runner register --no-interactive \
                  --instance https://git.cnas.dev \
                  --token "$(RUNNER_TOKEN)" \
                  --name k8s-runner-rooted \
                else
                  echo "Runner already registered, skipping.";
                fi
            env:
              - name: RUNNER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: token
              - name: LABELS
                value: "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
        containers:
          daemon:
            image:
              repository: docker
              tag: 29.3.1-dind@sha256:4d90f1f6c400315c2dba96d3ec93c01e64198395cbba04f79d12adce4f737029
            resources:
              requests:
                cpu: 10m
                memory: 194Mi
              limits:
                memory: 194Mi
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.7.2@sha256:5be962a66390e54f0e56c89aafee48f521538d996df7c4e61af77915a4c2bd86
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            command:
              - "sh"
              - "-c"
              - "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /config/config.yaml daemon"
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
        annotations:
          reloader.stakater.com/auto: "true"

    service:
      app:
        controller: *app
        ports:
          http:
            port: 45315

    persistence:
      config:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config

      certs:
        type: emptyDir
      cache:
        type: emptyDir
