---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${PVC_CLAIM:-${APP}}"
  labels:
    app.kubernetes.io/name: "${APP}"
spec:
  accessModes:
    - "${PVC_ACCESSMODES:-ReadWriteOnce}"
  resources:
    requests:
      storage: "${PVC_CAPACITY:-5Gi}"
  storageClassName: "${PVC_STORAGECLASS:-ceph-block}"
