---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: postgres-cluster
      namespace: databases
    - name: dragonfly-cluster
      namespace: databases
    - name: external-secrets
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/security/authentik/app
  postBuild:
    substitute:
      HOSTNAME: auth.kokoro.wtf
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
      # PVC_CLAIM: authentik-media
      # PVC_CAPACITY: "1Gi"
      # PVC_STORAGECLASS: ceph-filesystem
      # PVC_ACCESSMODES: ReadWriteMany
      # PVC_SNAPSHOTCLASS: csi-ceph-filesystem
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
