---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      namespace: &namespace databases
  interval: 30m
  path: ./kubernetes/apps/databases/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-barman-cloud
  namespace: &namespace databases
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 30m
  path: ./kubernetes/apps/databases/cloudnative-pg/barman-cloud
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres-cluster
  namespace: &namespace databases
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: openebs
      namespace: openebs
    - name: external-secrets
      namespace: security
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres
      namespace: databases
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres-immich
      namespace: databases
  interval: 30m
  path: ./kubernetes/apps/databases/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
