# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app forgejo
#   namespace: &namespace selfhosted
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   components:
#     - ../../../../components/volsync
#   dependsOn:
#     - name: external-secrets
#       namespace: security
#     - name: rook-ceph-cluster
#       namespace: rook-ceph
#   interval: 30m
#   path: ./kubernetes/apps/selfhosted/forgejo/app
#   postBuild:
#     substitute:
#       AUTH_HOST: auth.ctec.run
#       HOSTNAME: git.ctec.run
#       APP: *app
#       APP_UID: "2000"
#       APP_GID: "2000"
#       PVC_CAPACITY: 10Gi
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: *namespace
#   wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runner
  namespace: &namespace selfhosted
spec:
  # components:
  #   - ../../../../components/pvc
  interval: 1h
  path: ./kubernetes/apps/selfhosted/forgejo/runner
  postBuild:
    substitute:
      APP: *app
      # PVC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
