---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name libation
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Libation
        LIBATION_CONNECTION_STRING: postgresql://{{ .pg_user }}:{{ .pg_pass }}@{{ .postgres_host }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: libation
        INIT_POSTGRES_HOST: "{{ .postgres_host }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass }}"
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_PASS: "{{ .pg_pass }}"
  dataFrom:
    - extract:
        key: postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: libation
