---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app booklore
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 30m
  values:
    controllers:
      booklore:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [1010]
        initContainers:
          mariadb:
            image:
              repository: docker.io/library/mariadb
              tag: 12.2.2-noble
            env:
              MARIADB_DATABASE: *app
              MARIADB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: booklore_mariadb_password
              MARIADB_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: booklore_mariadb_root_password
              MARIADB_USER: *app
              PGID: 1000
              PUID: 1000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - |-
                        mariadb-admin ping --socket=/run/mysqld/mysqld.sock --user=root --password=$${MARIADB_ROOT_PASSWORD}
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              # NOTE: io_uring is blocked by the default containerd v2 seccomp profile
              # https://github.com/containerd/containerd/pull/9320
              seccompProfile: {type: Unconfined}
          wait-for-mariadb:
            image:
              repository: wait4x/wait4x
              tag: 3.6.0
            args:
              - "mysql"
              - "booklore:$(DB_PASSWORD)@tcp(localhost:3306)/booklore"
            env:
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: booklore_mariadb_password
        containers:
          booklore:
            image:
              repository: ghcr.io/booklore-app/booklore
              tag: v2.0.6
            command:
              - java
            args:
              - -jar
              - /app/app.jar
            env:
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: booklore_mariadb_password
              DATABASE_URL: jdbc:mariadb://localhost:3306/booklore
              DATABASE_USERNAME: booklore
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: &httpPort 6060
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *httpPort
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          booklore:
            booklore:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql
      nfs-nas-media:
        type: nfs
        server: shana.ctec.internal
        path: /mnt/tank/media
        advancedMounts:
          booklore:
            booklore:
              - path: /books
                subPath: booklore/books
              - path: /bookdrop
                subPath: booklore/bookdrop
      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          booklore:
            mariadb:
              - path: /run/mysqld
      tmpfs:
        type: emptyDir
        advancedMounts:
          booklore:
            booklore:
              - path: /tmp
                subPath: app
            mariadb:
              - path: /tmp
                subPath: mysql
    route:
      booklore:
        hostnames:
          - "{{ .Release.Name }}.kokoro.wtf"
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      booklore:
        ports:
          http:
            port: *httpPort
