---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - enp6s0
bondMode: active-backup
mtu: 9000
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.50
vlanID: 50
parent: bond0
mtu: 1500
