---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-nas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-nas-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .kopia_password }}"
  dataFrom:
    - extract:
        key: kopiur
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-b2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-b2-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .kopia_password }}"
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: kopia-b2
