---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: ${PVC_CAPACITY:=5Gi}
      mode: Ephemeral
      storageClassName: ceph-block
    securityContext:
      runAsUser: ${APP_UID:=2000}
      runAsGroup: ${APP_GID:=2000}
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  sources:
    - pvc:
        name: "${KOPIUR_CLAIM:-${APP}}"
  volumeSnapshotClassName: ${PVC_SNAPSHOTCLASS:=csi-ceph-blockpool}
