# docker-compose.yaml

services:
  server:
    image: codeberg.org/forgejo/forgejo:14.0.3@sha256:3bde16a366e57f37c09599b77ceb83ed05b1934f8224072f8140bc66cf243608
    container_name: forgejo-server
    restart: unless-stopped
    networks:
      app_ipvlan:
      forgejo:
    environment:
      USER_UID: 2000
      USER_GID: 2000
      TZ: America/New_York
      FORGEJO__admin__DISABLE_REGULAR_ORG_CREATION: true
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: database:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: ${FORGEJO_DATABASE_PASSWORD}
      FORGEJO__indexer__ISSUE_INDEXER_TYPE: bleve
      FORGEJO__indexer__REPO_INDXER_ENABLED: true
      FORGEJO__repository__DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
      FORGEJO__repository__DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
      FORGEJO__security__INTERNAL_TOKEN: "${FORGEJO_INTERNAL_TOKEN}"
      FORGEJO__security__SECRET_KEY: "${FORGEJO_SECRET_KEY}"
      FORGEJO__server__ROOT_URL: ${HOSTNAME}
    labels:
      traefik.enable: "true"
      traefik.http.services.forgejo.loadbalancer.server.port: 3000
      traefik.http.routers.forgejo.entrypoints: https
      traefik.http.routers.forgejo.rule: Host(`${HOSTNAME}`)
      traefik.http.routers.forgejo.tls: true
      traefik.http.routers.forgejo.service:
      traefik.tcp.routers.forgejo-ssh.rule: HostSNI('*')
      traefik.tcp.routers.forgejo-ssh.service: forgejo-ssh
      traefik.tcp.routers.forgejo-ssh.entrypoints: ssh-forgejo
      traefik.tcp.services.forgejo-ssh.loadbalancer.server.port: 22
    volumes:
      # replace the left-hand side from the ':' with your own path
      - /mnt/smoltank/apps/forgejo/data:/var/lib/gitea
    expose:
      - 3000
      - 22
    depends_on:
      - database
  database:
    image: postgres:17.5@sha256:864831322bf2520e7d03d899b01b542de6de9ece6fe29c89f19dc5e1d5568ccf
    container_name: forgejo-database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=forgejo
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=${FORGEJO_DATABASE_PASSWORD}
    networks:
      forgejo:
    volumes:
      # replace the left-hand side from the ':' with your own path
      - /mnt/smoltank/apps/forgejo/database:/var/lib/postgresql/data

networks:
  app_ipvlan:
    external: true
  forgejo:
    external: false
