---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
configs:
  traefik-config:
    file: ./config/traefik.yaml

networks:
  apps:
    name: apps

services:
  traefik:
    image: traefik:v3.6.9@sha256:9004e1cd1e33c5eb0b6ec02bc6cfda61fe9caca36751114b1c9c6662f01b264a
    container_name: traefik
    restart: always
    environment:
      TZ: America/New_York
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
    networks:
      apps:
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yaml
    volumes:
      - acme:/certs
      - ./config/dynamic:/dynamic
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  acme:
