---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
configs:
  traefik-config:
    file: ./config/traefik.yaml

networks:
  apps:
  app_ipvlan:
    driver: ipvlan
    name: app_ipvlan
    driver_opts:
      parent: br1
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
          ip_range: 192.168.5.128/25
          gateway: 192.168.5.1
services:
  traefik:
    image: traefik:v3.6.10@sha256:c549d482c55d7a797398562064f35428cc53e748d84d7190997930e7b31bcc32
    container_name: traefik
    restart: always
    environment:
      TZ: America/New_York
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
    networks:
      app_ipvlan:
        ipv4_address: 192.168.5.129
      apps:
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yaml
    volumes:
      - acme:/certs
      - ./config/dynamic:/dynamic
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  acme:
