---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
volumeType: directory
---
apiVersion: v1alpha1
kind: FilesystemTrimConfig
interval: 168h0m0s
---
apiVersion: v1alpha1
kind: FilesystemScrubConfig
interval: 168h0m0s
