---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  anime:
    base_url: http://animarr.default.svc.cluster.local
    api_key: !env_var ANIMARR_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: anime

    quality_profiles:
      - name: Remux-1080p - Anime
        trash_id: 20e0fc959f1f1704bed501f23bdae76f  # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
    # custom_format_groups:
    #   add:
    #     - trash_id: f4a0410a1df109a66d6e47dcadcce014
    #       select:
    #         - c9eafd50846d299b862ca9bb6ea91950
    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 100 # Adjust scoring as desired

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

  standard:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - name: WEB-1080p
        trash_id: 72dae194fc92bf828f32cde7744e51a1
        reset_unmatched_scores:
          enabled: true
      - name: WEB-2160p (Combined)
        trash_id: c4cadd6b35b95f62c3d47a408e53e2f7
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      - # FLUX trumps REPACKS
        trash_ids:
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
        assign_scores_to:
          - name: WEB-2160p (Combined)
            score: 100
      - # Unwanted
        trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p (Combined)

radarr:
  movies:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - name: HD Bluray + WEB
        trash_id: d1d67249d3890e49bc12e275d989a7e9
        reset_unmatched_scores:
          enabled: true
        qualities:
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBRip-1080p
              - WEBDL-1080p
      - name: UHD Bluray + WEB
        trash_id: 64fb5f9858489bdac2af690e27c8f42f  # UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBRip-1080p
              - WEBDL-1080p
    custom_format_groups:
      add:
        - trash_id: ff204bbcecdd487d1cefcefdbf0c278d  # [Optional] Golden Rule UHD
          # Mutually exclusive: enable only one of the following.
          exclude:
            - 839bea857ed2c0a8e084f3cbdbd65ecb  # x265 (no HDR/DV)
          select:
            # - dc98083864ea246d05a42df0d05f81cc  # x265 (HD)
        - trash_id: a3ac6af01d78e4f21fcb75f601ac96df  # [Unwanted] Unwanted Formats
