---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # OAUTH_CLIENT_ID: "{{ .oidc_id }}"
        # OAUTH_CLIENT_SECRET: "{{ .oidc_secret }}"
        # WEBUI_SECRET_KEY: "{{ .secret_key }}"
        # MEMINI_API_KEY: "{{ .memini_api_key }}"
        DATABASE_URL: "postgresql://{{ .pg_user }}:{{ .pg_pass }}@postgres-ai-rw.databases.svc.cluster.local/open_webui"

        # Postgres Init
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass }}"
        INIT_POSTGRES_PASS: "{{ .pg_pass }}"
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_HOST: "{{ .postgres_host }}"
        INIT_POSTGRES_DBNAME: "open_webui"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
