---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        security: |
          SECRET_KEY={{ .secret_key }}
          INTERNAL_TOKEN={{ .internal_token }}
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: "{{ .oidc_id }}"
        secret: "{{.oidc_secret }}"
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://k8s-schemas.kokoro.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .admin_user }}"
        email: "{{ .admin_email }}"
        password: "{{ .admin_pass }}"
  dataFrom:
    - extract:
        key: forgejo
